// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IGameNFT$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IGameNFT";
  readonly sourceName: "contracts/interfaces/IGameNFT.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint8","name":"badgeType","type":"uint8"}],"name":"BadgeAwarded","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint8","name":"cosType","type":"uint8"},{"indexed":false,"internalType":"uint8","name":"rarity","type":"uint8"}],"name":"CosmeticMinted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint8","name":"equipType","type":"uint8"},{"indexed":false,"internalType":"uint8","name":"rarity","type":"uint8"}],"name":"EquipmentMinted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint256","name":"dnaHash","type":"uint256"}],"name":"HeroMinted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":false,"internalType":"uint256","name":"sourceHeroId","type":"uint256"}],"name":"LegacyCoreCreated","type":"event"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IGameNFT.sol";
  readonly buildInfoId: "solc-0_8_28-1c458adc7f4ca8cb3d46d6464349923e00035ff3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IGameNFT"]: IGameNFT$Type;
    ["contracts/interfaces/IGameNFT.sol:IGameNFT"]: IGameNFT$Type;
  }
}